<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>coral-icon_Next_coral3-Icon coral3-Icon--si_2c4032</name>
   <tag></tag>
   <elementGuidId>df83e817-f691-4a47-9a80-d95f5c165149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='EditableToolbar']/button/coral-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.coral3-Button.coral3-Button--quiet.cq-editable-action > coral-icon.coral3-Icon.coral3-Icon--sizeS.coral3-Icon--add</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>coral-icon</value>
      <webElementGuid>bc848e87-d157-43e2-a812-1d0e5931f7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral3-Icon coral3-Icon--sizeS coral3-Icon--add</value>
      <webElementGuid>df0a2cb5-c648-4f33-acf3-98cec397087f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>12fbf597-e858-4b75-bb68-c6e8ee8502ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>33efe656-01e9-4a00-8f54-a83887899da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autoarialabel</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>3edf1d37-77d2-4fd8-b1c9-841efc727036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>964de40b-c7eb-45cc-9234-678748addb13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>619f5d20-d69c-4b49-8af8-151fa212a2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EditableToolbar&quot;)/button[@class=&quot;coral3-Button coral3-Button--quiet cq-editable-action&quot;]/coral-icon[@class=&quot;coral3-Icon coral3-Icon--sizeS coral3-Icon--add&quot;]</value>
      <webElementGuid>1616ce4a-4386-43f0-ae95-48e4a926cd92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EditableToolbar']/button/coral-icon</value>
      <webElementGuid>865c553b-2264-41da-9c19-69fe7a80802f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button/coral-icon</value>
      <webElementGuid>245853cc-6913-4773-b112-62d8a19c01c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
