<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>coral-selectlist-item_Article Paragraph</name>
   <tag></tag>
   <elementGuidId>63098bed-452c-4dfb-bb17-2a7fd0915d5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//coral-selectlist-item[@value='/apps/intel/commons/components/content/articleParagraph']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>coral-selectlist-item.coral3-SelectList-item.is-highlighted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>coral-selectlist-item</value>
      <webElementGuid>8795a00e-0891-485b-8081-2edd9163e1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral3-SelectList-item is-highlighted</value>
      <webElementGuid>a064e6ad-0c42-4dfd-98ab-9c27c93e2664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>003c3fb4-0149-4afb-8019-e24d105b5545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>/apps/intel/commons/components/content/articleParagraph</value>
      <webElementGuid>e61fbb2f-cfa8-44a0-a4ea-e860c3c4b8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>26a8cad9-08c6-4b3b-9e5e-e0baaa8527a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>32f0930d-7e15-4e00-b1bd-430d22c73437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2bdb8ba5-a600-4867-ad32-af329a2ef13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Article Paragraph</value>
      <webElementGuid>3dcbd613-387e-4a1c-9302-33bd734e1a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coral-id-622&quot;)/coral-selectlist-item[@class=&quot;coral3-SelectList-item is-highlighted&quot;]</value>
      <webElementGuid>f82f40d0-cc9e-4cad-bec1-9af662543cc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//coral-selectlist-item[@value='/apps/intel/commons/components/content/articleParagraph']</value>
      <webElementGuid>986ffb9b-1fdb-427e-9025-9b93049230a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//coral-selectlist-group[@id='coral-id-622']/coral-selectlist-item[4]</value>
      <webElementGuid>7bdfca5a-ff0a-4850-965b-1b6a9f10a946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Article Opt-In'])[1]/following::coral-selectlist-item[1]</value>
      <webElementGuid>1493e877-5fa5-45fa-b0c2-eca63d0f091d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Article Intro'])[1]/following::coral-selectlist-item[2]</value>
      <webElementGuid>b1c2aebe-3092-40ef-9f95-0b8bbbc40089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Call To Action Bar'])[1]/preceding::coral-selectlist-item[1]</value>
      <webElementGuid>3caaced6-d954-4bff-9842-bac14c43c78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chart Blade'])[1]/preceding::coral-selectlist-item[2]</value>
      <webElementGuid>a59b6488-d133-4837-9c23-aea8644e22a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Article Paragraph']/parent::*</value>
      <webElementGuid>b837c859-6e44-4ca1-9964-2ca3a934f690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//coral-selectlist-group/coral-selectlist-item[4]</value>
      <webElementGuid>7133c011-3335-4d05-938d-3b44ba20a1fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//coral-selectlist-item[(text() = 'Article Paragraph' or . = 'Article Paragraph')]</value>
      <webElementGuid>2dea444b-579a-4a92-bdbd-4d1b33db79e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
