<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>coral-icon_Article Paragraph_coral3-Icon co_f12185</name>
   <tag></tag>
   <elementGuidId>93db61f8-5cb1-4a89-8ca8-aef7cde7d873</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//coral-dialog-header[@id='coral-id-628']/div/button[4]/coral-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>coral-icon.coral3-Icon.coral3-Icon--sizeS.coral3-Icon--check</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>coral-icon</value>
      <webElementGuid>683ca4de-f6e2-4d53-9f55-b595b90a326b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral3-Icon coral3-Icon--sizeS coral3-Icon--check</value>
      <webElementGuid>b7988ffb-8af1-4843-a713-20386162f94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>check</value>
      <webElementGuid>8b327f28-e694-4c47-ab06-562d59f91021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>40d20f67-0a66-407a-b345-ee7c85038db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autoarialabel</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>df084cee-68f2-4170-92db-ad20383afba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f88f2c32-e351-41a1-b464-9f8bc2575d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>check</value>
      <webElementGuid>66fe6cf3-84fa-4b68-987d-6c76f00bec11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coral-id-628&quot;)/div[@class=&quot;cq-dialog-actions u-coral-pullRight&quot;]/button[@class=&quot;cq-dialog-header-action cq-dialog-submit coral3-Button coral3-Button--minimal&quot;]/coral-icon[@class=&quot;coral3-Icon coral3-Icon--sizeS coral3-Icon--check&quot;]</value>
      <webElementGuid>49ab40a0-d4f6-438f-b089-ca81dd23315f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//coral-dialog-header[@id='coral-id-628']/div/button[4]/coral-icon</value>
      <webElementGuid>71fa6df4-cff4-49f5-b926-d224e9dc3908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//coral-dialog-header/div/button[4]/coral-icon</value>
      <webElementGuid>78c95c64-f7c0-40bf-be47-d467fedf05d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
