<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Paragraph System Root_cq-Overlay cq-Ove_b79e5c</name>
   <tag></tag>
   <elementGuidId>f3912d91-68ad-44f7-bd79-0258ed24c706</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='OverlayWrapper']/div[8]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cq-Overlay.cq-Overlay--component.cq-droptarget.cq-Overlay--placeholder.is-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>97f5fff7-6167-42a7-af6b-242b30b9a1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>Editable</value>
      <webElementGuid>4c4f07a1-e33c-460a-ac39-3abcb852688f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-path</name>
      <type>Main</type>
      <value>/content/www/us/en/develop/test-jump/jcr:content/articlebladepar/*</value>
      <webElementGuid>5608ff87-3fb0-4ee4-abaf-1ad64f53051c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>59c205e2-5466-4587-84f8-83e194533334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5a5e0c21-cb10-4a34-a296-3df6ab3753a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cq-Overlay cq-Overlay--component cq-droptarget cq-Overlay--placeholder is-hover</value>
      <webElementGuid>8b8a404a-9658-403f-a9d4-144e57cea735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text</name>
      <type>Main</type>
      <value>Drag components here</value>
      <webElementGuid>4cf80eb0-ff22-4ae9-a932-fc16c5b24932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Paragraph System [Root]</value>
      <webElementGuid>cccbd023-498a-4edd-87df-50f7cce0f4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OverlayWrapper&quot;)/div[@class=&quot;cq-Overlay cq-Overlay--component cq-Overlay--container is-disabled&quot;]/div[@class=&quot;cq-Overlay cq-Overlay--component cq-droptarget cq-Overlay--placeholder is-hover&quot;]</value>
      <webElementGuid>a8c18222-9da6-4999-80d7-2513779342f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OverlayWrapper']/div[8]/div</value>
      <webElementGuid>8fefbec0-f758-4100-b3c6-9b649fadab1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div</value>
      <webElementGuid>3a0e9b17-0df6-4170-9a8e-49f744a2a8d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Paragraph System [Root]']</value>
      <webElementGuid>a9959ef2-06c2-49b4-be85-d84fcc94162d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
