<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jump Link Text_jumplinktext</name>
   <tag></tag>
   <elementGuidId>8231cd74-3df8-4c8e-bb66-2080f512c926</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='./jumplinktext']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;./jumplinktext&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1dccffb4-9937-438a-a2bc-919bf7f4aaa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral-Form-field coral-Textfield</value>
      <webElementGuid>98513775-3150-4598-89d5-db9a92055f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>124c7a02-c6a4-40ec-a12e-04099a7f4829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>./jumplinktext</value>
      <webElementGuid>aa48025a-0b83-478e-a5ff-f6127316d401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label_a1be5ad0-3dc3-497a-994f-baccc7b147e4 description_a1be5ad0-3dc3-497a-994f-baccc7b147e4</value>
      <webElementGuid>2c1151eb-ccf8-4914-ab7a-5734dec269ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;articleparagraph&quot;)/div[@class=&quot;coral-FixedColumn-column u-coral-padding u-coral-noMargin&quot;]/div[@class=&quot;coral-Form-fieldwrapper&quot;]/input[@class=&quot;coral-Form-field coral-Textfield&quot;]</value>
      <webElementGuid>711e5869-fcba-4dce-8768-32b021a46172</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='./jumplinktext']</value>
      <webElementGuid>489c4459-8a3c-4dd8-be44-9e771c012d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='articleparagraph']/div/div/input</value>
      <webElementGuid>7101a08a-57e4-426d-aec0-c488c8e2acb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//coral-dialog-content/div/div/div/input</value>
      <webElementGuid>1b144e9f-37cc-48cc-b93d-c77b18b73d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = './jumplinktext']</value>
      <webElementGuid>5f8492e4-30c2-421c-83eb-58935d099f17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
