<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>coral-list-item-content_Page</name>
   <tag></tag>
   <elementGuidId>fd4215cc-d8b1-4048-9078-dcf419ebf9ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//coral-popover-content[@id='coral-id-4015']/coral-anchorlist/a/div/div/coral-list-item-content</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>coral-list-item-content</value>
      <webElementGuid>db4a2f16-e9d8-4d43-9393-ae402e0bda1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral3-BasicList-item-content</value>
      <webElementGuid>05eb4074-fbb5-49c5-aec7-5a98c3241e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Page</value>
      <webElementGuid>481aeaf0-9c6b-4849-a774-3161f5b8e85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coral-id-4015&quot;)/coral-anchorlist[@class=&quot;coral3-BasicList coral3-AnchorList&quot;]/a[@class=&quot;cq-siteadmin-admin-createpage foundation-collection-action coral-Link coral3-BasicList-item coral3-AnchorList-item&quot;]/div[@class=&quot;coral3-BasicList-item-outerContainer&quot;]/div[@class=&quot;coral3-BasicList-item-contentContainer&quot;]/coral-list-item-content[@class=&quot;coral3-BasicList-item-content&quot;]</value>
      <webElementGuid>c29b68a9-c560-46d4-9b70-5a0111707787</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//coral-popover-content[@id='coral-id-4015']/coral-anchorlist/a/div/div/coral-list-item-content</value>
      <webElementGuid>f598f1d2-fe64-4458-9f5f-6817b8eb49aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[1]/following::coral-list-item-content[1]</value>
      <webElementGuid>51568c5a-9542-40e9-af9f-2b99eb3e340a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paste without children'])[1]/following::coral-list-item-content[1]</value>
      <webElementGuid>c1fc2aed-637d-4e5f-8e96-cf6520408643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site'])[1]/preceding::coral-list-item-content[1]</value>
      <webElementGuid>e7524657-dc83-4675-80b3-eb10703c0422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live Copy'])[1]/preceding::coral-list-item-content[2]</value>
      <webElementGuid>d60a3f8c-11b9-4b3a-9fc4-1cf484d65f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Page']/parent::*</value>
      <webElementGuid>d9710425-7feb-42c4-8060-f5d847175ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//coral-popover[2]/div[3]/coral-popover-content/coral-anchorlist/a/div/div/coral-list-item-content</value>
      <webElementGuid>0aecb60d-ff34-4f8a-8cb7-1f61ba5abdf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//coral-list-item-content[(text() = 'Page' or . = 'Page')]</value>
      <webElementGuid>08d4192d-100a-4c3b-ac37-04da257df2ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
