<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_icon-dsa.png</name>
   <tag></tag>
   <elementGuidId>97537aff-8ca7-4dd7-8387-93a21ba4d989</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-header1683958553973-message']/div[2]/div/nav/div/a/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.coral-ColumnView-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>071350c8-895a-402a-859e-bfd7acbc6b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral-ColumnView-label</value>
      <webElementGuid>1bba40ea-af3c-4054-98cc-ddec02206234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>icon-dsa.png</value>
      <webElementGuid>08f4f060-7cb2-4e77-9561-962a23f710fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-header1683958553973-message&quot;)/div[@class=&quot;coral-Pathbrowser-pickerPanel&quot;]/div[@class=&quot;coral-ColumnView&quot;]/nav[@class=&quot;coral-ColumnView-column&quot;]/div[@class=&quot;coral-ColumnView-column-content&quot;]/a[@class=&quot;coral-ColumnView-item&quot;]/div[@class=&quot;coral-ColumnView-label&quot;]</value>
      <webElementGuid>f0a7ebed-2dac-489e-9d07-9a5377880850</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-header1683958553973-message']/div[2]/div/nav/div/a/div[2]</value>
      <webElementGuid>8288cd5f-e7ce-47f7-b545-01d9ae01c0e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dam'])[1]/following::div[5]</value>
      <webElementGuid>1118c964-d854-4994-984d-c3c51451a4a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Path'])[1]/following::div[7]</value>
      <webElementGuid>06b1010d-54c2-4df1-b39d-c9bfa7317497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technology Provider'])[1]/preceding::div[2]</value>
      <webElementGuid>1481cd7d-9dd3-40de-ac61-7b44e32722f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pattern-library'])[1]/preceding::div[4]</value>
      <webElementGuid>f89828c2-1ecf-4c9b-8898-0b5eb69502a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='icon-dsa.png']/parent::*</value>
      <webElementGuid>dd57ea34-4f75-46d7-8de1-79c0ddda5655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]</value>
      <webElementGuid>3619e84b-5d99-404c-b4ba-438975ad32b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'icon-dsa.png' or . = 'icon-dsa.png')]</value>
      <webElementGuid>f71976a7-e082-4a3a-9a97-fe47a8eb9519</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
