<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Primary Business Owner_primaryOwner</name>
   <tag></tag>
   <elementGuidId>79953730-5e61-4c12-b965-eb5a2f1fa54b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='coral-6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#coral-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5bade766-6aac-496d-8ee1-a3d5b109d0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cc33b93c-61af-4cfd-a2a6-fc4a2f2e52fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>./primaryOwner</value>
      <webElementGuid>919b701c-9ce1-4c01-b93d-6291fdde342d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral-Textfield js-coral-Autocomplete-textfield coral-InputGroup-input autocomplete-has-suggestion-btn</value>
      <webElementGuid>993a5cce-4cde-4a3e-9a24-f17fc98c4320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label_56445e83-4449-4a53-834e-290a00f027b9 description_56445e83-4449-4a53-834e-290a00f027b9</value>
      <webElementGuid>379057d5-e3d8-42bc-9fda-64b8b5ed6c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0ec4cd92-ef19-4b74-912b-ca2376c57772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coral-6</value>
      <webElementGuid>dae46db6-2ed6-4c66-8cfa-f5dc92eccd61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>5e67bd39-8c22-4baa-b02d-da4ec54a5e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>coral-4</value>
      <webElementGuid>781103e9-5149-4a6b-9855-077e02033175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coral-6&quot;)</value>
      <webElementGuid>1b5acb24-c451-42c6-bf2b-cdf8c5aa6e9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='coral-6']</value>
      <webElementGuid>d2232ebd-c74f-44a8-8db7-8cc298e598b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coral-5']/input</value>
      <webElementGuid>a7920aaa-525c-4310-9b4e-7b4c4599b2dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/input</value>
      <webElementGuid>2894e7bc-7c50-4437-8570-455fd54006c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = './primaryOwner' and @id = 'coral-6']</value>
      <webElementGuid>68346915-9eee-4365-b9a6-1afb7880f939</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
