<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_System Page Title_jcrtitle</name>
   <tag></tag>
   <elementGuidId>40b2b07f-7b56-4e00-bfdb-598afcc53339</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='./jcr:title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;./jcr:title&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d028948-bb36-474d-a233-522c8847fcbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral-Form-field coral-Textfield</value>
      <webElementGuid>452e93d3-be2e-4f12-968e-7b51c57bc280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cq-msm-lockable</name>
      <type>Main</type>
      <value>jcr:title</value>
      <webElementGuid>be151fd7-9280-46e2-ad69-5d07fda1c2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0416898c-418d-4cd3-a38c-a23f04230be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>./jcr:title</value>
      <webElementGuid>a2fa4c0d-ae0f-4b1c-abbf-7d3c86c8518d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label_a7216ea0-eeca-4009-8009-5eaf72630c77 description_a7216ea0-eeca-4009-8009-5eaf72630c77</value>
      <webElementGuid>b0611f30-80ab-4344-81e5-fbb4483882f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2c9951cf-092d-47b3-8ae7-2de1d2bfff39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coral-1&quot;)/div[@class=&quot;coral-FixedColumn-column&quot;]/section[@class=&quot;coral-Form-fieldset&quot;]/div[@class=&quot;coral-Form-fieldwrapper&quot;]/input[@class=&quot;coral-Form-field coral-Textfield&quot;]</value>
      <webElementGuid>2d8f12bc-6c49-40c6-b551-187ed0808790</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='./jcr:title']</value>
      <webElementGuid>04e63aba-a284-4b73-8ad2-0c610521a1da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='coral-1']/div/section/div/input</value>
      <webElementGuid>f8363bf3-45c5-443f-a865-8bfda9a36133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/input</value>
      <webElementGuid>794da65d-68f0-4ec9-a147-d506d1cd0b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = './jcr:title']</value>
      <webElementGuid>8229bb1d-c84e-432d-8791-6ea65d6f5118</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
