<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Whitney, Cory (cory.whitneyintel.com)</name>
   <tag></tag>
   <elementGuidId>ff4992fd-23fe-40d2-a14a-f23e6a6f9103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='coral-4']/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.coral-SelectList-item.coral-SelectList-item--option.is-highlighted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2aeded2b-f16f-422e-b75a-744fbcf0488f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral-SelectList-item coral-SelectList-item--option is-highlighted</value>
      <webElementGuid>a7a1fcb6-c41c-44bb-b6f2-0f91afd7f40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Whitney, Cory (cory.whitney@intel.com)</value>
      <webElementGuid>9f34a21c-3684-4628-b27d-be48ab36de09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>1146ae8a-876b-4513-8687-f321a1d13852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6613af65-890d-45ed-a181-c1b51513be1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Whitney, Cory (cory.whitney@intel.com)</value>
      <webElementGuid>621e6198-9ab2-4698-8b78-785be648973e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coral-4&quot;)/li[@class=&quot;coral-SelectList-item coral-SelectList-item--option is-highlighted&quot;]</value>
      <webElementGuid>8d0c4a89-f7c9-4e12-b22e-83e98903d407</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='coral-4']/li</value>
      <webElementGuid>4b636409-da41-46b2-a1fb-8ad3c15239fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary Business Owner*'])[1]/following::li[1]</value>
      <webElementGuid>35bfbe45-cb45-454d-a03f-a4dec4b45207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration'])[1]/following::li[1]</value>
      <webElementGuid>e8c85699-3bfa-445c-80e4-5906cc049d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Path'])[1]/preceding::li[1]</value>
      <webElementGuid>f716dea9-3e57-4061-adc1-d1a82cf5ab25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dam'])[1]/preceding::li[1]</value>
      <webElementGuid>e3150fa7-d1ea-4d88-9a94-2445aaf51916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Whitney, Cory (cory.whitney@intel.com)']/parent::*</value>
      <webElementGuid>23ead899-4047-4b5d-87cd-dd51aa1963bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>878acd18-d1b5-4252-9d15-0ad14744c6c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Whitney, Cory (cory.whitney@intel.com)' or . = 'Whitney, Cory (cory.whitney@intel.com)')]</value>
      <webElementGuid>23f40c54-267b-4946-bff3-44552151314b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
