<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Normal</name>
   <tag></tag>
   <elementGuidId>5b70ddd5-424a-432a-bac2-cabb0a99846a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='CKEDITOR.tools.callFunction(159,this);return false;']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cke_335 > a.cke_combo_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a9c62090-4844-4053-8250-f196bfe865fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cke_combo_button</value>
      <webElementGuid>32e096a1-c863-4b7d-9747-02d040f971b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Paragraph Format</value>
      <webElementGuid>dcf4b80e-7265-4836-be10-7f942b11d85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>36a29138-3482-4478-a648-e67a4cd4796e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void('Paragraph Format')</value>
      <webElementGuid>4e00cc79-be10-43d9-a2f4-061245b80b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a416cd2e-d6af-4291-a692-17594a32d19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d3f29741-bfa4-46b9-950d-7e2b123a2126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>cke_335_label</value>
      <webElementGuid>615a2296-563a-46ab-a55c-5ad9690428f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>2c60358a-1808-4163-b96b-0c46d1ffb57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return CKEDITOR.tools.callFunction(160,event,this);</value>
      <webElementGuid>d6c040bc-38f7-4ffe-b58d-3b87039b3d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>return CKEDITOR.tools.callFunction(161,event);</value>
      <webElementGuid>2dc60e2b-3f9a-407b-abe5-1d961f128437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CKEDITOR.tools.callFunction(159,this);return false;</value>
      <webElementGuid>081f18c2-2aa1-41fa-a70a-45c457e86efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8c300c25-d469-4340-8be3-da9955d0f1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Normal</value>
      <webElementGuid>0998f06f-4a8a-44f0-b157-d680e768d44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cke_335&quot;)/a[@class=&quot;cke_combo_button&quot;]</value>
      <webElementGuid>04d42bb9-eeb4-4782-bc53-e3ee903a28d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='CKEDITOR.tools.callFunction(159,this);return false;']</value>
      <webElementGuid>b6189286-562c-493c-af8e-67c4a2e94d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cke_335']/a</value>
      <webElementGuid>21b8f445-3f81-4c76-a9ab-210a8024fcbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Normal, Format'])[1]/following::a[1]</value>
      <webElementGuid>89cc3ebb-64f5-47c4-a161-abc551a8af2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Styles'])[5]/following::a[1]</value>
      <webElementGuid>3e59c065-7b02-43cd-b321-2a3bfa77f698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='codeSnippet'])[1]/preceding::a[1]</value>
      <webElementGuid>2243ffe0-4ec0-42db-b263-e022fff91b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:void('Paragraph Format')&quot;)]</value>
      <webElementGuid>1eee1536-09e0-4232-a607-13d12cad578b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/a</value>
      <webElementGuid>8ee21d7d-226c-4e3f-aff8-6a41013c00e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Paragraph Format' and @href = concat(&quot;javascript:void(&quot; , &quot;'&quot; , &quot;Paragraph Format&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Normal' or . = 'Normal')]</value>
      <webElementGuid>ec51b0e3-b7aa-43b3-9d15-f4d4392c3ce3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
