<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next_coral3-Button coral3-Button--qu_15c00e</name>
   <tag></tag>
   <elementGuidId>94ccc5d2-1fc9-4d99-b8ee-4637f54f9a36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[93]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.coral3-Button.coral3-Button--quiet.cq-editable-action</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ef5fd14b-0fba-43e0-9dc2-d85fecca4158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>is</name>
      <type>Main</type>
      <value>coral-button</value>
      <webElementGuid>a0ae5436-5a9e-4e12-aeab-1e30f3be07f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral3-Button coral3-Button--quiet cq-editable-action</value>
      <webElementGuid>a49681bc-169f-437d-9897-c3480244bd6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>58cd9533-869e-46ab-927e-644f8be56fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>quiet</value>
      <webElementGuid>cb92686b-d4c5-4688-849d-dfb1d740b84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Insert component</value>
      <webElementGuid>c0816c15-0374-49e9-b8dc-73731672a3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>995aa355-9056-4d86-ac07-d02b2817c9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>INSERT</value>
      <webElementGuid>8e5e33c0-9e57-4e4d-83ac-a382dd3a09f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-path</name>
      <type>Main</type>
      <value>/content/www/us/en/develop/auto-test-jumplinks-1/jcr:content/articlebladepar/*</value>
      <webElementGuid>b79356eb-6094-4ceb-a9e8-2ee0ec0bd4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>d825fbd3-316b-4ac9-b0b4-498f8914eb4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ae34b5ef-2f56-48ac-b9ec-bf29f01b4d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EditableToolbar&quot;)/button[@class=&quot;coral3-Button coral3-Button--quiet cq-editable-action&quot;]</value>
      <webElementGuid>0b92b5fc-a4dd-44c0-8478-60bf235a26a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[93]</value>
      <webElementGuid>60fb4ca2-6c85-4b63-ab1b-ab998c66a68a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EditableToolbar']/button</value>
      <webElementGuid>a9b6b67b-2bfe-4565-b016-cd2c64964fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::button[5]</value>
      <webElementGuid>04dbbb00-5d6f-4b62-8fa5-ae4ec77757f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::button[6]</value>
      <webElementGuid>a034751a-45f7-4bc4-8073-b97734ab141b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intel Global Navigation Header [Root]'])[1]/preceding::button[2]</value>
      <webElementGuid>7457aa3f-0c1f-4f83-89b6-f9fc90024724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aggregation [Root]'])[1]/preceding::button[2]</value>
      <webElementGuid>4b2fe9a4-32e5-4a67-a081-b4096fc80bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button</value>
      <webElementGuid>7fb0b007-7f5f-4865-b3cf-db7e08616c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Insert component' and @type = 'button']</value>
      <webElementGuid>219cf062-13ff-4184-8afa-86db4edc5bc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
