<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>coral-icon_Next_coral3-Icon coral3-Icon--si_2c4032</name>
   <tag></tag>
   <elementGuidId>8ca26372-bc32-444b-8bdb-9080ddd66ef6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='EditableToolbar']/button/coral-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.coral3-Button.coral3-Button--quiet.cq-editable-action > coral-icon.coral3-Icon.coral3-Icon--sizeS.coral3-Icon--add</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>coral-icon</value>
      <webElementGuid>fc569896-c922-4a58-838c-ef3a9b1ee624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral3-Icon coral3-Icon--sizeS coral3-Icon--add</value>
      <webElementGuid>66744c0f-84a0-4451-a456-12b585eda619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>c2bc9231-faf6-4334-a4d0-11add11f7b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>8a0fb5be-26ba-4eaf-8dae-d34f513ed4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autoarialabel</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>7034dbf2-5d74-4157-a208-ea126d70e39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c3920097-f0ae-4c54-ac5e-f71daf20b409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>1aec75f8-6515-4eed-95aa-23b81f026f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EditableToolbar&quot;)/button[@class=&quot;coral3-Button coral3-Button--quiet cq-editable-action&quot;]/coral-icon[@class=&quot;coral3-Icon coral3-Icon--sizeS coral3-Icon--add&quot;]</value>
      <webElementGuid>2a811671-783a-4de9-9589-3886e11ca324</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EditableToolbar']/button/coral-icon</value>
      <webElementGuid>7cdd37c6-e90e-4607-8e50-a6c3b2230cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button/coral-icon</value>
      <webElementGuid>7d829d30-6374-467d-9f9c-a94df2f810f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
