<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>coral-icon_Article Paragraph_coral3-Icon co_f12185_1</name>
   <tag></tag>
   <elementGuidId>081cf1f9-6669-47aa-b391-288be674e390</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//coral-dialog-header[@id='coral-id-637']/div/button[4]/coral-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>coral-icon.coral3-Icon.coral3-Icon--sizeS.coral3-Icon--check</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>coral-icon</value>
      <webElementGuid>29348873-d635-4239-8a16-e57d93782cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral3-Icon coral3-Icon--sizeS coral3-Icon--check</value>
      <webElementGuid>0ae12c3d-d0dd-4bc7-bd24-5c7f1da80f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>check</value>
      <webElementGuid>93291b6b-c653-40b8-9e0a-6ab07eff5f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>0f4aa2d8-46e6-4ed9-996c-405e4e30313e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autoarialabel</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>f9c57dad-6863-4fe4-83dc-8bd4dce69c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4d579b89-20ac-46ed-8700-86c19ada14f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>check</value>
      <webElementGuid>c153edf7-530e-4b35-a50e-28a15945f3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coral-id-637&quot;)/div[@class=&quot;cq-dialog-actions u-coral-pullRight&quot;]/button[@class=&quot;cq-dialog-header-action cq-dialog-submit coral3-Button coral3-Button--minimal&quot;]/coral-icon[@class=&quot;coral3-Icon coral3-Icon--sizeS coral3-Icon--check&quot;]</value>
      <webElementGuid>ff89e629-5a97-4232-8dc9-b03e5e855db9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//coral-dialog-header[@id='coral-id-637']/div/button[4]/coral-icon</value>
      <webElementGuid>dcc1643b-178f-4282-8f12-17f891953dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//coral-dialog-header/div/button[4]/coral-icon</value>
      <webElementGuid>d02f89c2-e6c5-47bc-abd8-cfb45c2c96fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
