<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>coral-icon_test_coral3-Icon coral3-Icon--si_f3b805</name>
   <tag></tag>
   <elementGuidId>2de8fbb9-d414-4653-a27b-915cd3169b4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pageinfo-trigger']/coral-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>coral-icon.coral3-Icon.coral3-Icon--sizeS.coral3-Icon--properties</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>coral-icon</value>
      <webElementGuid>e7df43db-7798-4b7d-b73f-24a7fa2a183e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral3-Icon coral3-Icon--sizeS coral3-Icon--properties</value>
      <webElementGuid>098b4a03-908d-40b1-9cd4-3adecf5c98dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>properties</value>
      <webElementGuid>c38c4069-2d86-49b3-8767-722d7f0e1418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>c74d89cd-3e34-48af-827f-4ca832de4816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autoarialabel</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>cbd318d5-7a6a-4cd6-b016-0c4eda366520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>89879576-a218-4517-9ed9-54fc029fc308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>properties</value>
      <webElementGuid>a79564ba-4f9b-454d-aa71-e4eff5f33472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageinfo-trigger&quot;)/coral-icon[@class=&quot;coral3-Icon coral3-Icon--sizeS coral3-Icon--properties&quot;]</value>
      <webElementGuid>17a06023-5f83-4359-b397-2e6ac42e604b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='pageinfo-trigger']/coral-icon</value>
      <webElementGuid>6d8df929-b9ac-4207-b374-e22c29b97966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/coral-icon</value>
      <webElementGuid>4e0e846d-05f2-4f74-8af0-3aa5a658d946</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
