<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>coral-icon_Article Paragraph_coral3-Icon co_f12185</name>
   <tag></tag>
   <elementGuidId>002b3ad9-e8f7-4477-9606-033abbd50387</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//coral-dialog-header[@id='coral-id-628']/div/button[4]/coral-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>coral-icon.coral3-Icon.coral3-Icon--sizeS.coral3-Icon--check</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>coral-icon</value>
      <webElementGuid>a2437b38-b9de-4095-a785-ee6f1b9f6668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral3-Icon coral3-Icon--sizeS coral3-Icon--check</value>
      <webElementGuid>df37ddf8-72f1-4360-ae94-bc9bc1fd0248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>check</value>
      <webElementGuid>aa4584b3-f6c3-451d-994e-05d92e2e3ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>f067acca-86af-4408-a7c2-1010cb2d229f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autoarialabel</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>6b65b9ad-df88-48a4-9d8c-2868b984688d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cc1fe7b3-4d85-431b-b498-60f9dbd4d410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>check</value>
      <webElementGuid>2ecb6936-40ba-433a-92fa-08878feef2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coral-id-628&quot;)/div[@class=&quot;cq-dialog-actions u-coral-pullRight&quot;]/button[@class=&quot;cq-dialog-header-action cq-dialog-submit coral3-Button coral3-Button--minimal&quot;]/coral-icon[@class=&quot;coral3-Icon coral3-Icon--sizeS coral3-Icon--check&quot;]</value>
      <webElementGuid>eedc7392-5536-4d0c-b8ba-382dfb8f332e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//coral-dialog-header[@id='coral-id-628']/div/button[4]/coral-icon</value>
      <webElementGuid>32c05b01-1bef-4703-a6a7-4e026471d992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//coral-dialog-header/div/button[4]/coral-icon</value>
      <webElementGuid>3910e041-6a54-4393-a990-26d4e878e2d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
