<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>coral-selectlist-item_Article Paragraph</name>
   <tag></tag>
   <elementGuidId>052f26b0-823a-433b-a0a9-d880529f0e13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//coral-selectlist-item[@value='/apps/intel/commons/components/content/articleParagraph']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>coral-selectlist-item.coral3-SelectList-item.is-highlighted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>coral-selectlist-item</value>
      <webElementGuid>95ecff91-5eae-4677-a8ec-a2b1138a9f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral3-SelectList-item is-highlighted</value>
      <webElementGuid>086bed4c-c891-4b84-ae2f-e14f8992fdd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>aa996c16-05a3-41df-aae8-4e13c043378d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>/apps/intel/commons/components/content/articleParagraph</value>
      <webElementGuid>868cee3b-c75e-4505-9e98-f9528e2ae2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>86e41f20-189c-4aa6-9763-11b7507d6ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0a0f1d51-71de-45de-9798-c810666032bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9e964aa5-c289-4a01-a100-dded7aede198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Article Paragraph</value>
      <webElementGuid>d2c04992-4231-4e4d-ac4e-572daf546375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coral-id-622&quot;)/coral-selectlist-item[@class=&quot;coral3-SelectList-item is-highlighted&quot;]</value>
      <webElementGuid>def35f13-c62c-42eb-902a-b788e55a1a08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//coral-selectlist-item[@value='/apps/intel/commons/components/content/articleParagraph']</value>
      <webElementGuid>de6ba764-8465-4a2c-abde-59f361f32156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//coral-selectlist-group[@id='coral-id-622']/coral-selectlist-item[4]</value>
      <webElementGuid>007884a3-e174-4630-8119-e28eed73e24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Article Opt-In'])[1]/following::coral-selectlist-item[1]</value>
      <webElementGuid>5aaf0ce8-01d4-4800-8f89-90fde1c29330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Article Intro'])[1]/following::coral-selectlist-item[2]</value>
      <webElementGuid>6e44627c-214d-445b-b5c7-9fb10b38e65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Call To Action Bar'])[1]/preceding::coral-selectlist-item[1]</value>
      <webElementGuid>c9bc2fe6-5d89-443c-9c90-33833520cf9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chart Blade'])[1]/preceding::coral-selectlist-item[2]</value>
      <webElementGuid>c0a3668f-1d60-42f2-a59b-90656861f325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Article Paragraph']/parent::*</value>
      <webElementGuid>68c708be-6070-48bd-a718-60ac158c4f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//coral-selectlist-group/coral-selectlist-item[4]</value>
      <webElementGuid>c42f84e1-f2fb-4181-b00c-ff1a72f175b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//coral-selectlist-item[(text() = 'Article Paragraph' or . = 'Article Paragraph')]</value>
      <webElementGuid>4fed3ebd-2bf2-4f38-af02-053132e1bf66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
