<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>coral-icon_Next_coral3-Icon coral3-Icon--si_0df680</name>
   <tag></tag>
   <elementGuidId>65e2d25e-8f74-4f5f-a896-948323793f71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='EditableToolbar']/button/coral-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>coral-icon.coral3-Icon.coral3-Icon--sizeS.coral3-Icon--wrench</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>coral-icon</value>
      <webElementGuid>cb77eb95-c613-4c43-9d62-789d49ac5bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral3-Icon coral3-Icon--sizeS coral3-Icon--wrench</value>
      <webElementGuid>c5f29c61-1f40-4dbc-9145-298361ee8b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>wrench</value>
      <webElementGuid>fa84cb2c-1ec0-4f09-a022-9b9c7cb30635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>198fa095-52b5-4365-8914-214f271bcd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autoarialabel</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>39d542c5-4e75-45da-8d4c-d1ad1e2b8940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1a7c6e41-8c01-4ea7-92a6-148c4db33d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>wrench</value>
      <webElementGuid>3dde2e66-3786-42e1-b7d6-217d2e97de42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EditableToolbar&quot;)/button[@class=&quot;coral3-Button coral3-Button--quiet cq-editable-action&quot;]/coral-icon[@class=&quot;coral3-Icon coral3-Icon--sizeS coral3-Icon--wrench&quot;]</value>
      <webElementGuid>80767844-b326-40e4-b144-3b36ad53f2dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EditableToolbar']/button/coral-icon</value>
      <webElementGuid>df9ded82-b8ab-4469-84bb-2e275b2e7647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button/coral-icon</value>
      <webElementGuid>a3f34fc7-7115-4c09-b642-fe9d408e93e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
