<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Paragraph System Root_cq-Overlay cq-Ove_b79e5c</name>
   <tag></tag>
   <elementGuidId>e5aeb972-d3da-4732-8763-ed6082157de3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='OverlayWrapper']/div[8]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cq-Overlay.cq-Overlay--component.cq-droptarget.cq-Overlay--placeholder.is-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b9b4cfa8-19bb-4cc2-963d-0f0328288bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>Editable</value>
      <webElementGuid>88f9684a-8713-4b92-ad86-d5583bf543e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-path</name>
      <type>Main</type>
      <value>/content/www/us/en/develop/auto-test-jumplinks-1/jcr:content/articlebladepar/*</value>
      <webElementGuid>32a187a3-836b-4bff-a894-d2014dd3d706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>2c844f9d-d5ef-4d0a-81e3-e00214f3ac71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5f44cb57-7f77-4962-991c-f58dead168b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cq-Overlay cq-Overlay--component cq-droptarget cq-Overlay--placeholder is-hover</value>
      <webElementGuid>7e651857-5da6-4c95-bd8f-2011a408bc6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text</name>
      <type>Main</type>
      <value>Drag components here</value>
      <webElementGuid>a479e15f-22ac-4aeb-9a3f-78084b88aacc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Paragraph System [Root]</value>
      <webElementGuid>06637610-39d7-4eb4-a7b4-050abbe6dd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OverlayWrapper&quot;)/div[@class=&quot;cq-Overlay cq-Overlay--component cq-Overlay--container is-disabled&quot;]/div[@class=&quot;cq-Overlay cq-Overlay--component cq-droptarget cq-Overlay--placeholder is-hover&quot;]</value>
      <webElementGuid>6999d034-74fb-4bc5-b82d-101b89dde1fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OverlayWrapper']/div[8]/div</value>
      <webElementGuid>acc0b3f8-4387-4ca7-95cc-2b64d64e5ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div</value>
      <webElementGuid>b482e8da-2028-421a-8179-47fca91bba11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Paragraph System [Root]']</value>
      <webElementGuid>a74b102d-f5a2-436a-9971-c484e5c2ccc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
