<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Article Paragraph</name>
   <tag></tag>
   <elementGuidId>cf84468b-7505-4f17-bec7-2d1fce44315f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='OverlayWrapper']/div[8]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cq-Overlay.cq-Overlay--component.cq-draggable.cq-droptarget.cq-Overlay--placeholder.is-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>90f0b326-ce54-4a87-9e50-08f542e02831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>Editable</value>
      <webElementGuid>cff5f909-1239-4176-ac27-a33c2facbd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-path</name>
      <type>Main</type>
      <value>/content/www/us/en/develop/auto-test-jumplinks-1/jcr:content/articlebladepar/articleparagraph</value>
      <webElementGuid>aa711863-362d-4530-afbd-2124637a0404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>b6accdcd-aea0-45e5-aed6-e57b4541a3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>24c68f2d-2a06-4267-b965-2281de3d050c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cq-Overlay cq-Overlay--component cq-draggable cq-droptarget cq-Overlay--placeholder is-hover</value>
      <webElementGuid>49434abf-1af3-4b76-912c-416c63f810a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text</name>
      <type>Main</type>
      <value>Article Paragraph</value>
      <webElementGuid>11d92a1a-d665-45f5-897a-2bcf313ee590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Article Paragraph</value>
      <webElementGuid>c1dcdd7f-341f-41c4-953a-bd21ca4e58dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Article Paragraph</value>
      <webElementGuid>94ea6b63-ec0e-4dca-9596-52566d743aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OverlayWrapper&quot;)/div[@class=&quot;cq-Overlay cq-Overlay--component cq-Overlay--container is-disabled&quot;]/div[@class=&quot;cq-Overlay cq-Overlay--component cq-draggable cq-droptarget cq-Overlay--placeholder is-hover&quot;]</value>
      <webElementGuid>bd1ade27-91b2-4462-8379-d9bafd4b9389</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OverlayWrapper']/div[8]/div</value>
      <webElementGuid>f007f9da-41db-460d-b60d-1264296d0344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paragraph System [Root]'])[1]/following::div[1]</value>
      <webElementGuid>61560f3e-4608-4b27-835a-73d7d642dc0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Article Intro [Root]'])[1]/following::div[2]</value>
      <webElementGuid>6625e192-5bf2-429e-a94e-204d5ecbb91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Article Tags [Root]'])[1]/preceding::div[2]</value>
      <webElementGuid>a41790d9-9b56-4367-9fa5-2f2c3495c975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div</value>
      <webElementGuid>0c95cf92-6730-44e1-9af6-fe1213de4b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Article Paragraph' and (text() = 'Article Paragraph' or . = 'Article Paragraph')]</value>
      <webElementGuid>e9ec24a3-bf39-42bd-9b29-ce6476f3b369</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
