<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Link URL_cke_182_frame</name>
   <tag></tag>
   <elementGuidId>c6b12ef6-e32c-4848-9b61-6377baa613ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='cke_182_frame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cke_182_frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0e810c5a-e9b0-4622-9a00-d16f80c1520a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cke_182_frame</value>
      <webElementGuid>96c2cc3f-c398-4b07-a454-6965d6d246c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cke_panel_frame</value>
      <webElementGuid>5d2e1552-2d44-4d3f-bf51-e11602940081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>439caf43-4ebe-4723-98e6-2a2b9b3f39a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eb63db62-a955-437f-bc6c-de1eb3fc8131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cke_182_frame&quot;)</value>
      <webElementGuid>b2a089cd-1b20-44b4-bf55-b4f3f851f6d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='cke_182_frame']</value>
      <webElementGuid>b237d664-4034-4cf8-a102-dd90da4009d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cke_182']/iframe</value>
      <webElementGuid>1af7232d-a127-49f7-9548-81dc258aeed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/iframe</value>
      <webElementGuid>f69a94b2-8b45-446b-abd5-0dec78fa0404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'cke_182_frame']</value>
      <webElementGuid>ca03430a-dbbf-4d48-8302-19bdecccc6b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
