<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jump Link Text_jumplinktext</name>
   <tag></tag>
   <elementGuidId>117e8197-0261-4b7a-a90c-718bd378127b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='./jumplinktext']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;./jumplinktext&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8881c73-4a90-4b9b-ae2f-e98cfe93b4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral-Form-field coral-Textfield</value>
      <webElementGuid>cb55e5a9-2793-4aaf-abd8-b647ffc6b3b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7bb1e16a-4e4c-43c0-b0ef-56dba487cf1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>./jumplinktext</value>
      <webElementGuid>beb15115-780b-4a26-894b-e8ab40ea5fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label_c91960d5-7d97-40a3-a34c-d3d75e4d3225 description_c91960d5-7d97-40a3-a34c-d3d75e4d3225</value>
      <webElementGuid>5dc677bb-d41b-43f0-a2d1-260eaf0f5b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;articleparagraph&quot;)/div[@class=&quot;coral-FixedColumn-column u-coral-padding u-coral-noMargin&quot;]/div[@class=&quot;coral-Form-fieldwrapper&quot;]/input[@class=&quot;coral-Form-field coral-Textfield&quot;]</value>
      <webElementGuid>803ad103-7082-46be-9975-b99eb6d5f920</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='./jumplinktext']</value>
      <webElementGuid>71cfd950-421c-42dc-aab7-1a87b7373517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='articleparagraph']/div/div/input</value>
      <webElementGuid>f41acb2e-38fa-46f4-baba-ba3e5f63a40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//coral-dialog-content/div/div/div/input</value>
      <webElementGuid>891200a2-c4a7-43aa-bf7a-46468372252a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = './jumplinktext']</value>
      <webElementGuid>27a580db-dd3b-418d-b4f0-7d365a022adc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
