<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_paragraph1</name>
   <tag></tag>
   <elementGuidId>65b6ce56-9bfb-40d3-99af-a93fcf5c28b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='inpage-navigation']/ul/li/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.word_arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>743bd2ca-e5d7-4d45-8d96-a1e768bab09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>word_arrow</value>
      <webElementGuid>18d82f82-83b9-4660-976a-546deec8769b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>paragraph1</value>
      <webElementGuid>75aeb7ee-70c0-4bf2-b0f9-52620f28a0a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inpage-navigation&quot;)/ul[@class=&quot;inpage-nav&quot;]/li[@class=&quot;parent nochildren&quot;]/a[@class=&quot;jumplink&quot;]/span[@class=&quot;word_arrow&quot;]</value>
      <webElementGuid>0bc2cf92-2610-414c-9f83-d873cf38d493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Author/Page_test/iframe_Next_ContentFrame</value>
      <webElementGuid>d57057a2-e76b-458e-8aea-2ad0c9d794c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inpage-navigation']/ul/li/a/span</value>
      <webElementGuid>cc42b7d3-eba6-409e-a005-b32140c9d38f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firefox'])[1]/following::span[1]</value>
      <webElementGuid>97180e31-f770-448f-a953-5da1dc6193c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edge'])[1]/following::span[1]</value>
      <webElementGuid>d5a06b0c-0ccc-4aee-85e0-5f763f9ceec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='paragraph2'])[1]/preceding::span[1]</value>
      <webElementGuid>f4cda58d-3bf3-49a4-a079-0b2b78242891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By'])[1]/preceding::span[2]</value>
      <webElementGuid>93d7d798-42b1-4af3-b311-3f42accb318e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='paragraph1']/parent::*</value>
      <webElementGuid>48799d72-5c05-486d-a647-9deb66be669e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div/div/div/div[2]/ul/li/a/span</value>
      <webElementGuid>c0ae8972-9084-4f0e-b899-507c3e6191e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'paragraph1' or . = 'paragraph1')]</value>
      <webElementGuid>ee05365d-4abb-4ade-8799-a215ca5c6692</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
