<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Normal_cke_combo_arrow</name>
   <tag></tag>
   <elementGuidId>966f9348-b2de-4f62-b95c-3a6c91ec00c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cke_11']/a/span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cke_11 > a.cke_combo_button > span.cke_combo_open > span.cke_combo_arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3a6f72d9-361e-4bf7-8f63-418403301be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cke_combo_arrow</value>
      <webElementGuid>dbd06521-b675-40f2-9d3e-ca74756446a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cke_11&quot;)/a[@class=&quot;cke_combo_button&quot;]/span[@class=&quot;cke_combo_open&quot;]/span[@class=&quot;cke_combo_arrow&quot;]</value>
      <webElementGuid>c11e09da-21de-462d-b63f-e6458db1f4a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cke_11']/a/span[2]/span</value>
      <webElementGuid>b454daf4-4fcb-4d4d-bce0-a2cd1441a41c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/a/span[2]/span</value>
      <webElementGuid>d71a92aa-f40c-49de-8eb1-df79019a32a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
