<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_paragraph2</name>
   <tag></tag>
   <elementGuidId>9cd1ee14-5dee-46e7-afca-7616c851f88c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='inpage-navigation']/ul/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd37c77d-1428-4c66-9896-46d1660693b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>word_arrow</value>
      <webElementGuid>b5eb4947-07c9-4644-8604-f2c850a53371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>paragraph2</value>
      <webElementGuid>bcb2be5c-739c-4aef-abcc-ed7a643642d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inpage-navigation&quot;)/ul[@class=&quot;inpage-nav&quot;]/li[@class=&quot;parent nochildren&quot;]/a[@class=&quot;jumplink&quot;]/span[@class=&quot;word_arrow&quot;]</value>
      <webElementGuid>c038e8dc-808c-451f-a714-7d197f6b5335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Author/Page_test/iframe_Next_ContentFrame</value>
      <webElementGuid>67459f59-a879-4d60-87e5-dbb1f59be311</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inpage-navigation']/ul/li[2]/a/span</value>
      <webElementGuid>e90c9e5f-37b4-4770-a9a3-2b17d529b90d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='paragraph1'])[1]/following::span[1]</value>
      <webElementGuid>4cc8b8ae-ef41-42fa-a8ad-a6377c2dea29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firefox'])[1]/following::span[2]</value>
      <webElementGuid>7b7aad02-5522-4a8a-87d1-856cbd32fe0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By'])[1]/preceding::span[1]</value>
      <webElementGuid>db3d8262-c820-481e-b97d-13ca29f43732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='paragraph1'])[2]/preceding::span[3]</value>
      <webElementGuid>d80bee1f-ad96-4aa7-9687-661045c8d76f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='paragraph2']/parent::*</value>
      <webElementGuid>b03b8e48-4906-4031-94a3-655adaccc77d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div/div/div/div[2]/ul/li[2]/a/span</value>
      <webElementGuid>87f26497-5dd0-4aff-aac3-d93996306bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'paragraph2' or . = 'paragraph2')]</value>
      <webElementGuid>b3796792-5ae8-43e9-96b7-00c1e3cb8be4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
