<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_No</name>
   <tag></tag>
   <elementGuidId>b62c3dfc-0bd9-4281-97cb-e90d50408fb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='coral-id-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#coral-id-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>798dbdff-c122-4fb4-98c0-e8de764f64ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>is</name>
      <type>Main</type>
      <value>coral-button</value>
      <webElementGuid>a5d7d452-db5b-4c94-9588-f26c6c59e391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral3-Button coral3-Button--secondary coral3-Button--block coral3-Select-button</value>
      <webElementGuid>8daa8c65-60eb-4c10-a338-caecd1d1b400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>7013e37a-6107-481a-8e37-cfe029411093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>secondary</value>
      <webElementGuid>699aadd5-6421-449b-afdb-a1d32ee4cc9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tracking</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c37bb83c-bca6-4f29-a83b-bd75ed31c65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>handle</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>88edb03e-c6c5-40cb-8f3a-914d7ab34efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f53b017c-651c-4a93-baff-0cac8bcc7a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3ef0b783-108b-4bbc-bc8f-acc8829a2cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coral-id-2</value>
      <webElementGuid>690037e3-2b39-49c2-98c4-acc9cefa1250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>coral-id-3</value>
      <webElementGuid>ce0d3bdb-3f92-47fd-b553-38fbb47c0f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e2d52fdf-d9f5-4a0b-98c4-477aad7022dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label_1ddcca26-6b37-4631-83ca-d7a6a86d17f5 coral-id-4</value>
      <webElementGuid>b84763b4-61b6-4666-b67b-385f9f776b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  
  No
</value>
      <webElementGuid>4b87b08c-facc-47e0-a42f-ab5385ec3d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coral-id-2&quot;)</value>
      <webElementGuid>9b0d2810-c37b-4df4-bd79-2dd0cca40c7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='coral-id-2']</value>
      <webElementGuid>cb202450-a0ad-40e0-97f9-fb2cc8198a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coral-397']/div/div[3]/coral-select/button</value>
      <webElementGuid>a79c8145-b16b-4d69-8c59-d5d604f5604e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Will this page contain in-page navigation?'])[1]/following::button[1]</value>
      <webElementGuid>16de1ed8-0c9e-41b8-bb68-6fb5f2f1abfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable Right Rail Module'])[1]/following::button[1]</value>
      <webElementGuid>04ffe0b8-8b3d-4021-a669-91477ad83398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[5]/preceding::button[1]</value>
      <webElementGuid>f67c1182-9c4e-4c74-af68-b8c104a1f36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//coral-select/button</value>
      <webElementGuid>a920820b-2a6a-4a9b-9e2f-3e2dd5e9fa5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'coral-id-2' and (text() = '
  
  No
' or . = '
  
  No
')]</value>
      <webElementGuid>c071fd94-13c8-40d3-94d5-5804ec101c7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
