<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>coral-selectlist-item_Yes</name>
   <tag></tag>
   <elementGuidId>ff35bc2f-c6cb-4ce3-ad6f-5eaa95d8ab4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//coral-selectlist-item[@value='yes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>coral-selectlist-item.coral3-SelectList-item.is-highlighted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>coral-selectlist-item</value>
      <webElementGuid>95bf7d7b-5e7a-4beb-868d-64e3abfa1f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral3-SelectList-item is-highlighted</value>
      <webElementGuid>4f920a8f-78f9-4c6f-9cec-e97ec75ffc8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d71593d7-67a7-4267-8aac-12ccf42831dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>88979857-3bc0-45ab-9138-f22a7838cac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>dff1aa32-be5a-4826-9e1a-4ad6867b7447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c0f48297-8c6f-4fad-a1ce-4118cf403712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ae367850-02ee-4b8f-8007-c086eecc9d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>6b5f6736-0a89-4672-93dd-cfa7d33c0211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coral-id-3&quot;)/coral-selectlist-item[@class=&quot;coral3-SelectList-item is-highlighted&quot;]</value>
      <webElementGuid>96962f12-ab54-4f82-bfdc-27d274966de3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//coral-selectlist-item[@value='yes']</value>
      <webElementGuid>aceb8851-1441-4f05-bb61-9eac06b7e9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//coral-selectlist[@id='coral-id-3']/coral-selectlist-item[2]</value>
      <webElementGuid>99ae6512-a48e-4d59-92b3-101a13d162cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[5]/following::coral-selectlist-item[1]</value>
      <webElementGuid>8aba4b23-4796-4fee-a2a6-48b9b8072874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[4]/following::coral-selectlist-item[2]</value>
      <webElementGuid>98f1de92-26da-4dbe-b141-d4c40a8066fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[6]/preceding::coral-selectlist-item[1]</value>
      <webElementGuid>48165c3d-ae38-4f4f-bb5c-0085337a29de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[4]/preceding::coral-selectlist-item[1]</value>
      <webElementGuid>e0c4d35e-d24f-4abb-b9c9-cc5c52cb3e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//coral-selectlist-item[2]</value>
      <webElementGuid>8a2dabde-ec84-4dcf-9080-e804ab171342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//coral-selectlist-item[(text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>7128b031-9932-4f81-93cc-0f3430d03807</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
